apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  namespace: default
  labels:
    app: test
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi