apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-beta1
  namespace: default
  labels:
    app: test-1
spec:
  storageClassName: rook-ceph-block-1
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi